services:
  wavelog-db:
    environment:
      - TZ=America/Chicago
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=wavelog
      - MARIADB_USER=wavelog
      - MARIADB_PASSWORD=*#Xixj^r@$8c6R!4F^o98i
  wavelog:
    build:
      args:
        APP_UID: 1003
        APP_GID: 1004
    user: 1003:1004
    environment:
      - TZ=America/Chicago
      - CI_ENV=docker
      - CHROOT_DIRECTORY=/home/dockeradmin/wavelog/app-data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      #- "traefik.http.routers.wavelog.entrypoints=http"
      #- "traefik.http.routers.wavelog.rule=Host(`wavelog.we1der.com`)"
      #- "traefik.http.routers.wavelog.service=wavelog-wavelog"
      #- "traefik.http.middlewares.wavelog-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.wavelog.middlewares=wavelog-https-redirect"
      - "traefik.http.routers.wavelog-secure.entrypoints=https"
      - "traefik.http.routers.wavelog-secure.rule=Host(`wavelog.we1der.com`)"
      - "traefik.http.routers.wavelog-secure.service=wavelog-wavelog"
      - "traefik.http.routers.wavelog-secure.tls=true"
      - "traefik.http.routers.wavelog-secure.tls.certResolver=letsencrypt"
  dxcache:
    environment:
      MAXCACHE: 500
      WEBPORT: 8192
      WAVELOG_URL: https://wavelog.we1der.com/index.php/api/lookup
      WAVELOG_KEY: wl0ba30f128007a
      WEBURL: /dxc
      DXHOST: dxc.ai9t.com
      DXPORT: 7300
      DXCALL: WE1DER
      POTA_INTEGRATION: true
      POTA_POLLING_INTERVAL: 60

volumes:
  wavelog-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wavelog-db #/srv/docker/volumes/wavelog/dbdata
  wavelog-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wavelog-config #/srv/docker/volumes/wavelog/app-data
  wavelog-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wavelog-uploads #/srv/docker/volumes/wavelog/app-data
  wavelog-userdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wavelog-userdata #/srv/docker/volumes/wavelog/app-data
